export enum ModelType {
  IDENTIFIER = 'IDENTIFIER',

  REFERENCE = 'REFERENCE',
  REFERENCES = 'REFERENCES',

  TYPE_NAME = 'TYPE_NAME',
  NON_VOID_TYPE_NAME = 'NON_VOID_TYPE_NAME',
  VOID_TYPE_NAME = 'VOID_TYPE_NAME',

  PARAM = 'PARAM',
  PARAMS = 'PARAMS',

  ATTRIBUTE = 'ATTRIBUTE',
  METHOD = 'METHOD',

  PROPS_BLOCK = 'PROPS_BLOCK',
  STATE_BLOCK = 'STATE_BLOCK',
  VALUE_BLOCK = 'VALUE_BLOCK',

  PROVIDER_NAME = 'PROVIDER_NAME',
  PROVIDER_BODY = 'PROVIDER_BODY',
  PROVIDER_FIELDS = 'PROVIDER_FIELDS',
  PROVIDER_BLOCK = 'PROVIDER_BLOCK',

  ROUTE_NAME = 'ROUTE_NAME',
  ROUTE_BODY = 'ROUTE_BODY',
  ROUTE_ENTRY = 'ROUTE_ENTRY',
  ROUTE_ENTRIES = 'ROUTE_ENTRIES',
  ROUTES_LIST = 'ROUTES_LIST',
  ROUTE_BLOCK = 'ROUTE_BLOCK',

  LAYOUT_NAME = 'LAYOUT_NAME',
  LAYOUT_BODY = 'LAYOUT_BODY',
  LAYOUT_BLOCK = 'LAYOUT_BLOCK',

  COMPONENT_NAME = 'COMPONENT_NAME',
  COMPONENT_BODY = 'COMPONENT_BODY',
  COMPONENT_BLOCK = 'COMPONENT_BLOCK',
  COMPONENTS_BLOCK = 'COMPONENTS_BLOCK',

  APP_NAME = 'APP_NAME',
  APP_BODY = 'APP_BODY',
  APP_BLOCK = 'APP_BLOCK',

  WIDGET_BLOCK = 'WIDGET_BLOCK',
  WIDGETS_BLOCK = 'WIDGETS_BLOCK',

  IMPORT_LIST = 'IMPORT_LIST',
  IMPORT_PACKAGE = 'IMPORT_PACKAGE',
  IMPORT_SOURCE = 'IMPORT_SOURCE',

  IMPORT_CLAUSE = 'IMPORT_CLAUSE',

  GENERATE_NAME = 'GENERATE_NAME',
  GENERATE_BODY = 'GENERATE_BODY',

  GENERATE_CLAUSE = 'GENERATE_CLAUSE',

  FRONTEND_SPEC = 'FRONTEND_SPEC'
}
