export enum ModelType {
  IDENTIFIER = 'IDENTIFIER',

  REFERENCE = 'REFERENCE',
  REFERENCES = 'REFERENCES',

  TYPE_NAME = 'TYPE_NAME',
  NON_VOID_TYPE_NAME = 'NON_VOID_TYPE_NAME',
  VOID_TYPE_NAME = 'VOID_TYPE_NAME',

  PARAM = 'PARAM',
  PARAMS = 'PARAMS',

  ATTRIBUTE = 'ATTRIBUTE',
  METHOD = 'METHOD',

  PROPS = 'PROPS',
  STATE = 'STATE',
  VALUE = 'VALUE',

  PROVIDER = 'PROVIDER',
  PROVIDER_NAME = 'PROVIDER_NAME',
  PROVIDER_BODY = 'PROVIDER_BODY',
  PROVIDER_FIELDS = 'PROVIDER_FIELDS',

  ROUTE = 'ROUTE',
  ROUTE_NAME = 'ROUTE_NAME',
  ROUTE_BODY = 'ROUTE_BODY',
  ROUTE_ENTRY = 'ROUTE_ENTRY',
  ROUTE_ENTRIES = 'ROUTE_ENTRIES',
  ROUTES_LIST = 'ROUTES_LIST',

  LAYOUT = 'LAYOUT',
  LAYOUT_NAME = 'LAYOUT_NAME',
  LAYOUT_BODY = 'LAYOUT_BODY',

  COMPONENT = 'COMPONENT',
  COMPONENT_NAME = 'COMPONENT_NAME',
  COMPONENT_BODY = 'COMPONENT_BODY',
  COMPONENTS = 'COMPONENTS',

  APP = 'APP',
  APP_NAME = 'APP_NAME',
  APP_BODY = 'APP_BODY',

  WIDGET = 'WIDGET',
  WIDGETS = 'WIDGETS',

  FRONTEND = 'FRONTEND'
}
